### ISSUE TITLE
All plugins should be pre-selected options

### ISSUE THREAD

**Issue by paulvi** [de-jcup/jcup-eclipse-plugins-collection#4]
I maybe missed communicating the point in https://github.com/de-jcup/egradle/issues/334
that the collection marketplace entry should give option to install any of the plugins or all of them,
by having every feature name listed in marketplace entry as optional and pre-selected.

Currently it looks like there is new feature, that installs all, without a way to unselected some parts.

![image](https://user-images.githubusercontent.com/1614482/40634617-819e7158-6328-11e8-9254-0a990c995ab9.png)

MP should be configured with many feature names:

![](https://user-images.githubusercontent.com/1614482/35956872-3359c926-0cd3-11e8-89b9-0e5a0eecda96.png)

**Comment by de-jcup** [comment]
Very funny: When I tested the composite site (local....) It behaves like: 
![image](https://user-images.githubusercontent.com/11644753/40643575-e5a00dea-6320-11e8-8fe8-0635440c3b4a.png)

I did no tested the behaviour with MPC client because my thought was: "its just an update site and will work as on local..." - my mistake...

In my opinion the mpc should handle this better. Its more convenient to have a composite site defined by code inside a GIT repository than clicking around in a UI.

I will enter an issue at eclipse.org.

**Comment by de-jcup** [comment]
Opened issue : https://bugs.eclipse.org/bugs/show_bug.cgi?id=535254

**Comment by paulvi** [comment]
Can you show screenshot or "jcup collection" marketplace entry?

It should have all feature IDs listed.

MPC lists only those listed features, while update site may have many more (e.g. dependency)
and they will be organizing into update site categories/folders by default.

**Comment by paulvi** [comment]
> So IMHO the MPC client should handle this in same way as done when a local update site. 

No, it will not. Because generally local or remote update site does not have listed features.

One can think about MP entry features as a way to skip one step of usual install (where we need to select what features we need)

**Comment by de-jcup** [comment]
Mmhh. okay. So I will try to do your approach with defining every feature in MPC.

**Comment by de-jcup** [comment]
closed https://bugs.eclipse.org/bugs/show_bug.cgi?id=535254
